---
Name: dynamicelementsconfig
---

Dynamic\Elements\Elements\ElementSlideshow:
  extensions:
    - Dynamic\FlexSlider\ORM\FlexSlider
Dynamic\FlexSlider\Model\SlideImage:
  extensions:
    - Dynamic\Elements\ORM\ElementSlideshowSlideDataExtension
Dynamic\Elements\Model\BaseElementObject:
  extensions:
    - Dynamic\Elements\ORM\ElementPageLink